blog/urls.py
from django.conf.urls import url
from blog.views import *

app_name = 'blog'

urlpatterns = [
    url(r'^$',PostLV.as_view(),name='index'),

    url(r'^post/$',PostLV.as_view(),name='post_list'),

    url(r'^post/(?P<slug>[-\w]+)/$',PostDV.as_view(),name='post_detail'),

    url(r'^archive/$',PostAV.as_view(),name='post_archive'),

    url(r'^(?P<year>\d{4})/$',PostYAV.as_view(),name='post_year_archive'),

    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$',PostDAV.as_view(),name='post_day_archive'),

    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),

    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

    url(r'^search/$', SearchFormView.as_view(), name='search'),
]

bookmark/urls.py
from django.conf.urls import url
from bookmark.views import BookmarkLV, BookmarkDV

app_name = 'bookmark'

urlpatterns = [

    url(r'^$', BookmarkLV.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),

]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import ListView,DetailView
from django.conf.urls.static import static
from django.conf import settings

from django.urls import path

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

from bookmark.models import Bookmark


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),

   # url(r'^bookmark/$', ListView.as_view(model=Bookmark), name='index'),
   # url(r'^bookmark/(?P<pk>\d+)/$', DetailView.as_view(model=Bookmark), name='detail'),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
from django.conf.urls import url
from photo.views import *

app_name = 'photo'
urlpatterns = [
    url(r'^$', AlbumLV.as_view(model=Album), name='index'),

    url(r'^album/$', ListView.as_view(model=Album), name='album_list'),

    url(r'^album/(?P<pk>\d+)/$', DetailView.as_view(model=Album), name='album_detail'),

    url(r'^photo/(?P<pk>\d+)/$', DetailView.as_view(model=Photo), name='photo_detail'),
]

blog/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.urls import reverse
from tagging.fields import TagField

# Create your models here.

@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField('TITLE',max_length=50)
    slug = models.SlugField('SLUG',unique=True,allow_unicode=True,help_text='one word for title alias')
    description = models.CharField('DESCRIPTION',max_length=100,blank=True,help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date',auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date',auto_now=True)
    tag = TagField()

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'my_post'
        ordering = ('-modify_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',args=(self.slug,))

    def get_previous_post(self):
        return self.get_previous_by_modify_date()

    def get_next_post(self):
        return self.get_next_by_modify_date()

bookmark/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.

class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)

    def __str__(self):
        return "%s %s" %(self.title, self.url)

photo/models.py
from django.db import models
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible

from photo.fields import ThumbnailImageField

# Create your models here.

@python_2_unicode_compatible
class Album(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField('One Line Description', max_length=100, blank=True)

    class Mete:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))

class Photo(models.Model):
    album = models.ForeignKey('Album',on_delete=models.CASCADE,)
    title = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('Photo Description', blank=True)
    upload_date = models.DateTimeField('Upload Date', auto_now_add=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

#이거 html <form>태그랑 역할이 같음

blog/views.py
from django.shortcuts import render

from django.views.generic import ListView,DetailView, TemplateView
from tagging.models import Tag, TaggedItem
from tagging.views import TaggedObjectList
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView,TodayArchiveView

from django.views.generic.edit import FormView
from blog.forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render

from blog.models import Post

# Create your views here.

class TagTV(TemplateView):
    template_name = 'tagging/tagging_cloud.html'

class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2

class PostDV(DetailView):
    model = Post

class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_date'

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_date'

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_date'


class PostTOL(TaggedObjectList):
    model = Post
    template_name = 'tagging/tagging_post_list.html'

class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        schWord = '%s' % self.request.POST['search_word']
        post_list = Post.objects.filter(Q(title__icontains=schWord) | Q(description__icontains=schWord) | Q(content__icontains=schWord)).distinct()
        #disntinct()는 중복제거
        context = {}
        context['form'] = form
        context['search_term'] = schWord
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)

bookmark/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views.generic import ListView,DetailView
from bookmark.models import Bookmark

# Create your views here.

class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

mysite/views.py
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

#--- TemplateView
class HomeView(TemplateView):
    template_name = 'home.html'

#--- User Creation
class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'

photo/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from photo.models import Album, Photo

# Create your views here.

class AlbumLV(ListView):
    model = Album

class AlbumDV(DetailView):
    model = Album

class PhotoDV(DetailView):
    model = Photo

blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %}post_all.html{% endblock %}

{% block content %}
<div id="content">

<h1>Blog List</h1>

{% for post in posts %}
    <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
    {{ post.modify_date|date:"N d, Y" }}
    <p>{{ post.description }}</p>
{% endfor %}

<br/>

<div>
    <span>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
        {% endif %}

        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
        {% endif %}
    </span>

</div>

</div>
{% endblock %}

blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}post_archive.html{% endblock %}

{% block content %}
<div id="content">

<h1>Post Archives until {% now "N d, Y" %}</h1>
<ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year-{{ date|date:"Y" }}</a></li>
    {% endfor %}
</ul>
<br/>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

</div>
{% endblock %}

blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %}post_archive_day.html{% endblock %}

{% block content %}
<div id="content">

<h1>Post Archives for {{ day|date:"N d, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

</div>
{% endblock %}

blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %}post_archive_month.html{% endblock %}

{% block content %}
<div id="content">

<h1>Post Archives for {{ month|date:"N, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

</div>
{% endblock %}

blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %}post_archive_year.html{% endblock %}

{% block content %}
<div id="content">

<h1>Post Archives for {{ year|date:"Y" }}</h1>

<ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:"F" }}</a></li>
    {% endfor %}
</ul>
<br/>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}post_detail.html{% endblock %}
{% block content %}
<div id="content">

<h2>{{ object.title }}</h2>

<p class="other_posts">
   {% if object.get_previous_by_modify_date %}
   <a href="{{ object.get_previous_post.get_absolute_url }}" title="View previous post"> &laquo;--{{ object.get_previous_post }}</a>
   {% endif %}

   {% if object.get_next_by_modify_date %}
   | <a href="{{ object.get_next_post.get_absolute_url }}" title="View next post"> {{ object.get_next_post }}--&raquo;</a>
   {% endif %}
</p>

<p class="date">{{ object.modify_date|date:"j F Y" }}</p>
<br>

<div class="body">
   {{ object.content|linebreaks }}
</div>

<div>
  <b>TAGS: </b>
  {% load tagging_tags %}
  {% tags_for_object object as tags %}
  {% for tag in tags %}
  <a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}</a>
  {% endfor %}
  <a href="{% url 'blog:tag_cloud' %}"><i>[ TagCloud ]</i></a>
</div>

<br>
<div>
{% load disqus_tags %}
{% disqus_show_comments %}
</div>

</div>
{% endblock %}

blog/templates/blog/post_search.html
{% extends "base.html" %}

{% block title %}post_search.html{% endblock %}

{% block content %}
<div id="content">
    <h1>Blog Search</h1>
    <form action="." method="post"> {% csrf_token %}
    {{ form.as_table }}
        <input type="submit" value="Submit">
    </form>

    <br><br>
    {% if object_list %}
    {% for post in object_list %}
    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
    {{ post.modify_date|date:"N d, Y" }}
    <p>{{ post.description }}</p>
    {% endfor %}

{% elif search_term %}
<b><i>Serach Word({{ search_term }}) Not Found !</i></b>
{% endif %}
</div>
{% endblock %}

blog/templates/tagging/tagging_cloud.html
{% extends "base.html" %}

{% block title %}tagging_cloud.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "tagging/tag.css" %}{% endblock %}

{% block content %}
<div id="content">

<h1>Blog Tag Cloud</h1>

<div class="tag-cloud">
    {% load tagging_tags %}
    {% tag_cloud_for_model blog.Post as tags with steps=6 min_count=1 distribution=log %}
    {% for tag in tags %}
    <span class="tag-{{tag.font_size}}">
        <a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}({{tag.font_size}})</a>
    </span>
    {% endfor %}
</div>

</div>
{% endblock %}

blog/templates/tagging/tagging_post_list.html
{% extends "base.html" %}

{% block title %}tagging_post_list.html{% endblock %}

{% block content %}
<div id="content">
    <h1>Posts for tag - {{ tag.name }}</h1>

    {% for post in object_list %}
    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
    {{ post.modify_date|date:"N d, Y" }}
    <p>{{ post.descriptions }}</p>
    {% endfor %}
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %}Bookmark Detail{% endblock %}

{% block content %}
<div id="content">

    <h1>
        {{ object.title }}
    </h1>

    <ul>
        <li>URL : <a href="{{ object.url }}">{{ object.url }}</a></li>
    </ul>

</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}
<head>

{% block title %}Django Bookmark List{% endblock %}
{% load staticfiles %}
{% block extrastyle %}{% static "css/bookmark_list.css" %}{% endblock %}
</head>
{% block content %}
<body>
<div id="content">
    <h1>Bookmark List</h1>

    <ul class="rectangle-list">
        {% for bookmark in object_list %}
            <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
        {% endfor %}
    </ul>
</div>
</body>
{% endblock %}

photo/templates/photo/album_detail.html
{% extends "base.html" %}

{% block title %}album_detail.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<div id="content">
    <h2 style="display: inline">{{ object.name }}</h2>
    &emsp;<b><i>{{ object.description }}</i></b>

    <hr>

    <div class="album-detail">
        {% for photo in object.photo_set.all %}
        <div class="album-detail-photo">
            <a href="{{ photo.get_absolute_url }}">
                <img src="{{ photo.image.thumb_url }}" class="thumbnail">
            </a>
            <li>{{ photo.title }}</li>
            <li>{{ photo.upload_date|date:"Y-m-d" }}</li>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

photo/templates/photo/album_list.html
{% extends "base.html" %}

{% block title %}album_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<div id="content">

    {% for item in object_list %}

    <div class="clear_float">
        <h2 style="display:inline"><a href="{% url 'photo:album_detail' item.id %}">{{ item.name }}</a></h2>
        &emsp;<b><i>{{ item.description }}</i></b>
    </div>

    <hr>

    <div class="album-list">
        {% for photo in item.photo_set.all|slice:":5" %}
        <div class="album-list-photo">
            <a href="{{ photo.get_absolute_url }}">
                <img src="{{ photo.image.thumb_url }}" alt="thumbnail">
            </a>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends "base.html" %}

{% block title %}photo_detail.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<div id="content">

    <h2>{{ object.title }}</h2>

    <table class="photo-detail">
        <tr>
            <td>
                <a href="{{ object.image.url }}">
                    <img src="{{ object.image.url }}" style="max-width: 100%">
                </a>
            </td>

            <td>
                <ul>
                    <li>Photo Description</li>
                    {% if object.description %}<p>{{ object.description|linebreaks }}</p>
                    {% else %}<p>(blank)</p>{% endif %}
                    <li>Date Uploaded</li>
                    <p>{{ object.upload_date }}</p>
                    <li>Album Name</li>
                    <p><a href="{% url 'photo:album_detail' object.album.id %}">{{ object.album.name }}</a></p>
                </ul>
            </td>
        </tr>
    </table>
</div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <title>{% block title %} Django Web Programming {% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static "css/base.css" %}" type="text/css">
    <link rel="stylesheet" href="{% block extrastyle %}{% endblock %}">
    <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    <script src="script.js"></script>
</head>

<body>
<div id="header">
    <h2 class="maintitle">Soogyeong's JSP Study</h2>

    {% if user.is_active %} # 1
    <h4 class="welcome">Welcome,
        <strong>{% firstof user.get_short_name user.get_username %}</strong> # 2
        <a href="{% url 'password_change' %}">Change Password</a>
        <a href="{% url 'logout' %}">Logout</a>
    </h4>
    {% else %}
    <h4 class="welcome">Welcome, Anonymous
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'register' %}">Register</a>
    </h4>
    {% endif %}
</div>

<div id="cssmenu">
    <ul>
    <li><a href="{% url 'home' %}">HOME</a></li>
    <li><a href="{% url 'bookmark:index' %}">BOOKMARK</a></li>
    <li><a href="{% url 'blog:index' %}">BLOG</a></li>
    <li><a href="{% url 'photo:index' %}">PHOTO</a></li>
    <li><a href="#">ADD&bigtriangledown;</a>
      <ul class="dropdown">
            <li><a href="#">BOOKMARK</a></li>
            <li><a href="#">BLOG</a></li>
            <li><a href="#">PHOTO</a></li>
        </ul>
    </li>
    <li><a href="#">CHANGE&bigtriangledown;</a>
       <ul class="dropdown">
            <li><a href="#">BOOKMARK</a></li>
            <li><a href="#">BLOG</a></li>
            <li><a href="#">PHOTO</a></li>
        </ul>
    </li>
    <li><a href="{% url 'blog:post_archive' %}">ARCHIVE</a></li>
    <li><a href="{% url 'blog:search' %}">SEARCH</a></li>
    <li><a href="{% url 'admin:index' %}">ADMIN</a></li>
    </ul>
</div>
{% block content %}{% endblock %}
{% block footer %}{% endblock %}
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}
<div id="content_home">
    <div id="home_img">
        <section class="container">
		<input id="select1" type="radio" name="radioBanner" class="banner_input1" checked="">
		<label for="select1" class="label_btn1">1</label>

		<input id="select2" type="radio" name="radioBanner" class="banner_input2">
		<label for="select2" class="label_btn2">2</label>



		<ul class="banner_mask">
			<li>
				<a href="#none"><img src="{% static 'img/main.jpg' %}" width="100%" height="400px" alt="첫번째 배너이미지"></a>
			</li>
			<li>
				<a href="#none"><img src="{% static 'img/sub.jpg' %}" width="100%" height="400px"  alt="두번째 배너이미지"></a>
			</li>
		</ul>

		</section>
    </div>

	<table id="applist">
        <tr>
        <td class="rectangle-list"><b><a href="{% url 'bookmark:index' %}">Bookmark</a></b></td>
            <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
            <td class="Edit"><a href="#">Add</a></td>
            <td class="Edit"><a href="#">Change</a></td>
        </tr>

        <tr>
            <td class="rectangle-list"><b><a href="{% url 'blog:index' %}">Blog</a></b></td>
            <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
            <td class="Edit"><a href="#">Add</a></td>
            <td class="Edit"><a href="#">Change</a></td>
        </tr>
        <tr>
            <td class="rectangle-list"><b><a href="#">Photo</a></b></td>
            <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
            <td class="Edit"><a href="#">Add</a></td>
            <td class="Edit"><a href="#">Change</a></td>
        </tr>
    </table>

</div>
{% endblock content %}

{% block footer %}
<div id="footer">
    &copy; SG 2018
</div>
{% endblock footer %}